package ImpJavaProgram.ImpJavaProgram.json;

import java.io.FileNotFoundException;

import org.json.JSONArray;
import org.json.JSONObject;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonIOException;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonSyntaxException;

public class GetPlatformsData {
	public static String currentDir = System.getProperty("user.dir");

	public static void main(String[] args) throws JsonSyntaxException, JsonIOException, FileNotFoundException {
//		Gson gson = new Gson();
//		JsonElement json = gson.fromJson(new FileReader(currentDir + "/jsonFile/GetPlatformsData.json"), JsonElement.class);
//		String result = gson.toJson(json);
//		System.out.println("Result : -> " + result);
		String jsonFile = "{\n"
				+ "	\"slack\": {\n"
				+ "		\"ok\": true,\n"
				+ "		\"channels\": [{\n"
				+ "			\"id\": \"CBXQ2PUBT\",\n"
				+ "			\"name\": \"general\",\n"
				+ "			\"is_channel\": true,\n"
				+ "			\"is_group\": false,\n"
				+ "			\"is_im\": false,\n"
				+ "			\"is_mpim\": false,\n"
				+ "			\"is_private\": false,\n"
				+ "			\"created\": 1532709785,\n"
				+ "			\"is_archived\": false,\n"
				+ "			\"is_general\": true,\n"
				+ "			\"unlinked\": 0,\n"
				+ "			\"name_normalized\": \"general\",\n"
				+ "			\"is_shared\": false,\n"
				+ "			\"is_org_shared\": false,\n"
				+ "			\"is_pending_ext_shared\": false,\n"
				+ "			\"pending_shared\": [],\n"
				+ "			\"parent_conversation\": null,\n"
				+ "			\"creator\": \"UBXKC3GGY\",\n"
				+ "			\"is_ext_shared\": false,\n"
				+ "			\"shared_team_ids\": [\"TBY71ASJX\"],\n"
				+ "			\"pending_connected_team_ids\": [],\n"
				+ "			\"is_member\": true,\n"
				+ "			\"topic\": {\n"
				+ "				\"value\": \"Company-wide announcements and work-based matters\",\n"
				+ "				\"creator\": \"UBXKC3GGY\",\n"
				+ "				\"last_set\": 1532709785\n"
				+ "			},\n"
				+ "			\"purpose\": {\n"
				+ "				\"value\": \"This channel is for workspace-wide communication and announcements. All members are in this channel.\",\n"
				+ "				\"creator\": \"UBXKC3GGY\",\n"
				+ "				\"last_set\": 1532709785\n"
				+ "			},\n"
				+ "			\"previous_names\": [],\n"
				+ "			\"num_members\": 13\n"
				+ "		}, {\n"
				+ "			\"id\": \"CBYB017BL\",\n"
				+ "			\"name\": \"random\",\n"
				+ "			\"is_channel\": true,\n"
				+ "			\"is_group\": false,\n"
				+ "			\"is_im\": false,\n"
				+ "			\"is_mpim\": false,\n"
				+ "			\"is_private\": false,\n"
				+ "			\"created\": 1532709785,\n"
				+ "			\"is_archived\": false,\n"
				+ "			\"is_general\": false,\n"
				+ "			\"unlinked\": 0,\n"
				+ "			\"name_normalized\": \"random\",\n"
				+ "			\"is_shared\": false,\n"
				+ "			\"is_org_shared\": false,\n"
				+ "			\"is_pending_ext_shared\": false,\n"
				+ "			\"pending_shared\": [],\n"
				+ "			\"parent_conversation\": null,\n"
				+ "			\"creator\": \"UBXKC3GGY\",\n"
				+ "			\"is_ext_shared\": false,\n"
				+ "			\"shared_team_ids\": [\"TBY71ASJX\"],\n"
				+ "			\"pending_connected_team_ids\": [],\n"
				+ "			\"is_member\": false,\n"
				+ "			\"topic\": {\n"
				+ "				\"value\": \"Non-work banter and water cooler conversation\",\n"
				+ "				\"creator\": \"UBXKC3GGY\",\n"
				+ "				\"last_set\": 1532709785\n"
				+ "			},\n"
				+ "			\"purpose\": {\n"
				+ "				\"value\": \"A place for non-work-related flimflam, faffing, hodge-podge or jibber-jabber you'd prefer to keep out of more focused work-related channels.\",\n"
				+ "				\"creator\": \"UBXKC3GGY\",\n"
				+ "				\"last_set\": 1532709785\n"
				+ "			},\n"
				+ "			\"previous_names\": [],\n"
				+ "			\"num_members\": 10\n"
				+ "		}, {\n"
				+ "			\"id\": \"C022MFXSHGT\",\n"
				+ "			\"name\": \"bot4\",\n"
				+ "			\"is_channel\": true,\n"
				+ "			\"is_group\": false,\n"
				+ "			\"is_im\": false,\n"
				+ "			\"is_mpim\": false,\n"
				+ "			\"is_private\": false,\n"
				+ "			\"created\": 1621576353,\n"
				+ "			\"is_archived\": false,\n"
				+ "			\"is_general\": false,\n"
				+ "			\"unlinked\": 0,\n"
				+ "			\"name_normalized\": \"bot4\",\n"
				+ "			\"is_shared\": false,\n"
				+ "			\"is_org_shared\": false,\n"
				+ "			\"is_pending_ext_shared\": false,\n"
				+ "			\"pending_shared\": [],\n"
				+ "			\"parent_conversation\": null,\n"
				+ "			\"creator\": \"U01GEHNCEKT\",\n"
				+ "			\"is_ext_shared\": false,\n"
				+ "			\"shared_team_ids\": [\"TBY71ASJX\"],\n"
				+ "			\"pending_connected_team_ids\": [],\n"
				+ "			\"is_member\": false,\n"
				+ "			\"topic\": {\n"
				+ "				\"value\": \"\",\n"
				+ "				\"creator\": \"\",\n"
				+ "				\"last_set\": 0\n"
				+ "			},\n"
				+ "			\"purpose\": {\n"
				+ "				\"value\": \"\",\n"
				+ "				\"creator\": \"\",\n"
				+ "				\"last_set\": 0\n"
				+ "			},\n"
				+ "			\"previous_names\": [],\n"
				+ "			\"num_members\": 2\n"
				+ "		}, {\n"
				+ "			\"id\": \"C023BEQ5DJA\",\n"
				+ "			\"name\": \"backend-channel\",\n"
				+ "			\"is_channel\": true,\n"
				+ "			\"is_group\": false,\n"
				+ "			\"is_im\": false,\n"
				+ "			\"is_mpim\": false,\n"
				+ "			\"is_private\": false,\n"
				+ "			\"created\": 1622460212,\n"
				+ "			\"is_archived\": false,\n"
				+ "			\"is_general\": false,\n"
				+ "			\"unlinked\": 0,\n"
				+ "			\"name_normalized\": \"backend-channel\",\n"
				+ "			\"is_shared\": false,\n"
				+ "			\"is_org_shared\": false,\n"
				+ "			\"is_pending_ext_shared\": false,\n"
				+ "			\"pending_shared\": [],\n"
				+ "			\"parent_conversation\": null,\n"
				+ "			\"creator\": \"U01G6GUDELW\",\n"
				+ "			\"is_ext_shared\": false,\n"
				+ "			\"shared_team_ids\": [\"TBY71ASJX\"],\n"
				+ "			\"pending_connected_team_ids\": [],\n"
				+ "			\"is_member\": true,\n"
				+ "			\"topic\": {\n"
				+ "				\"value\": \"\",\n"
				+ "				\"creator\": \"\",\n"
				+ "				\"last_set\": 0\n"
				+ "			},\n"
				+ "			\"purpose\": {\n"
				+ "				\"value\": \"this is for testing\",\n"
				+ "				\"creator\": \"U01G6GUDELW\",\n"
				+ "				\"last_set\": 1622460213\n"
				+ "			},\n"
				+ "			\"previous_names\": [],\n"
				+ "			\"num_members\": 5\n"
				+ "		}, {\n"
				+ "			\"id\": \"C02RV7D5EBS\",\n"
				+ "			\"name\": \"automation\",\n"
				+ "			\"is_channel\": true,\n"
				+ "			\"is_group\": false,\n"
				+ "			\"is_im\": false,\n"
				+ "			\"is_mpim\": false,\n"
				+ "			\"is_private\": false,\n"
				+ "			\"created\": 1639741552,\n"
				+ "			\"is_archived\": false,\n"
				+ "			\"is_general\": false,\n"
				+ "			\"unlinked\": 0,\n"
				+ "			\"name_normalized\": \"automation\",\n"
				+ "			\"is_shared\": false,\n"
				+ "			\"is_org_shared\": false,\n"
				+ "			\"is_pending_ext_shared\": false,\n"
				+ "			\"pending_shared\": [],\n"
				+ "			\"parent_conversation\": null,\n"
				+ "			\"creator\": \"U02K9E1RAUD\",\n"
				+ "			\"is_ext_shared\": false,\n"
				+ "			\"shared_team_ids\": [\"TBY71ASJX\"],\n"
				+ "			\"pending_connected_team_ids\": [],\n"
				+ "			\"is_member\": false,\n"
				+ "			\"topic\": {\n"
				+ "				\"value\": \"\",\n"
				+ "				\"creator\": \"\",\n"
				+ "				\"last_set\": 0\n"
				+ "			},\n"
				+ "			\"purpose\": {\n"
				+ "				\"value\": \"testing\",\n"
				+ "				\"creator\": \"U02K9E1RAUD\",\n"
				+ "				\"last_set\": 1639741553\n"
				+ "			},\n"
				+ "			\"previous_names\": [],\n"
				+ "			\"num_members\": 3\n"
				+ "		}, {\n"
				+ "			\"id\": \"C02SD63J0F8\",\n"
				+ "			\"name\": \"newprivatechannel\",\n"
				+ "			\"is_channel\": true,\n"
				+ "			\"is_group\": false,\n"
				+ "			\"is_im\": false,\n"
				+ "			\"is_mpim\": false,\n"
				+ "			\"is_private\": true,\n"
				+ "			\"created\": 1641269907,\n"
				+ "			\"is_archived\": false,\n"
				+ "			\"is_general\": false,\n"
				+ "			\"unlinked\": 0,\n"
				+ "			\"name_normalized\": \"newprivatechannel\",\n"
				+ "			\"is_shared\": false,\n"
				+ "			\"is_org_shared\": false,\n"
				+ "			\"is_pending_ext_shared\": false,\n"
				+ "			\"pending_shared\": [],\n"
				+ "			\"parent_conversation\": null,\n"
				+ "			\"creator\": \"U01TY0SDDS4\",\n"
				+ "			\"is_ext_shared\": false,\n"
				+ "			\"shared_team_ids\": [\"TBY71ASJX\"],\n"
				+ "			\"pending_connected_team_ids\": [],\n"
				+ "			\"is_member\": true,\n"
				+ "			\"topic\": {\n"
				+ "				\"value\": \"\",\n"
				+ "				\"creator\": \"\",\n"
				+ "				\"last_set\": 0\n"
				+ "			},\n"
				+ "			\"purpose\": {\n"
				+ "				\"value\": \"just for testing\",\n"
				+ "				\"creator\": \"U01TY0SDDS4\",\n"
				+ "				\"last_set\": 1641269908\n"
				+ "			},\n"
				+ "			\"num_members\": 3\n"
				+ "		}, {\n"
				+ "			\"id\": \"C02SHQFUM39\",\n"
				+ "			\"name\": \"post-messages-bot\",\n"
				+ "			\"is_channel\": true,\n"
				+ "			\"is_group\": false,\n"
				+ "			\"is_im\": false,\n"
				+ "			\"is_mpim\": false,\n"
				+ "			\"is_private\": false,\n"
				+ "			\"created\": 1641476135,\n"
				+ "			\"is_archived\": false,\n"
				+ "			\"is_general\": false,\n"
				+ "			\"unlinked\": 0,\n"
				+ "			\"name_normalized\": \"post-messages-bot\",\n"
				+ "			\"is_shared\": false,\n"
				+ "			\"is_org_shared\": false,\n"
				+ "			\"is_pending_ext_shared\": false,\n"
				+ "			\"pending_shared\": [],\n"
				+ "			\"parent_conversation\": null,\n"
				+ "			\"creator\": \"U01FK2DNRLM\",\n"
				+ "			\"is_ext_shared\": false,\n"
				+ "			\"shared_team_ids\": [\"TBY71ASJX\"],\n"
				+ "			\"pending_connected_team_ids\": [],\n"
				+ "			\"is_member\": true,\n"
				+ "			\"topic\": {\n"
				+ "				\"value\": \"\",\n"
				+ "				\"creator\": \"\",\n"
				+ "				\"last_set\": 0\n"
				+ "			},\n"
				+ "			\"purpose\": {\n"
				+ "				\"value\": \"\",\n"
				+ "				\"creator\": \"\",\n"
				+ "				\"last_set\": 0\n"
				+ "			},\n"
				+ "			\"previous_names\": [],\n"
				+ "			\"num_members\": 4\n"
				+ "		}, {\n"
				+ "			\"id\": \"C02TAKHTLQG\",\n"
				+ "			\"name\": \"testing\",\n"
				+ "			\"is_channel\": true,\n"
				+ "			\"is_group\": false,\n"
				+ "			\"is_im\": false,\n"
				+ "			\"is_mpim\": false,\n"
				+ "			\"is_private\": false,\n"
				+ "			\"created\": 1641292066,\n"
				+ "			\"is_archived\": false,\n"
				+ "			\"is_general\": false,\n"
				+ "			\"unlinked\": 0,\n"
				+ "			\"name_normalized\": \"testing\",\n"
				+ "			\"is_shared\": false,\n"
				+ "			\"is_org_shared\": false,\n"
				+ "			\"is_pending_ext_shared\": false,\n"
				+ "			\"pending_shared\": [],\n"
				+ "			\"parent_conversation\": null,\n"
				+ "			\"creator\": \"U01FK2DNRLM\",\n"
				+ "			\"is_ext_shared\": false,\n"
				+ "			\"shared_team_ids\": [\"TBY71ASJX\"],\n"
				+ "			\"pending_connected_team_ids\": [],\n"
				+ "			\"is_member\": true,\n"
				+ "			\"topic\": {\n"
				+ "				\"value\": \"\",\n"
				+ "				\"creator\": \"\",\n"
				+ "				\"last_set\": 0\n"
				+ "			},\n"
				+ "			\"purpose\": {\n"
				+ "				\"value\": \"\",\n"
				+ "				\"creator\": \"\",\n"
				+ "				\"last_set\": 0\n"
				+ "			},\n"
				+ "			\"previous_names\": [],\n"
				+ "			\"num_members\": 3\n"
				+ "		}, {\n"
				+ "			\"id\": \"C02V18JRTAB\",\n"
				+ "			\"name\": \"todo-testing\",\n"
				+ "			\"is_channel\": true,\n"
				+ "			\"is_group\": false,\n"
				+ "			\"is_im\": false,\n"
				+ "			\"is_mpim\": false,\n"
				+ "			\"is_private\": false,\n"
				+ "			\"created\": 1643101657,\n"
				+ "			\"is_archived\": false,\n"
				+ "			\"is_general\": false,\n"
				+ "			\"unlinked\": 0,\n"
				+ "			\"name_normalized\": \"todo-testing\",\n"
				+ "			\"is_shared\": false,\n"
				+ "			\"is_org_shared\": false,\n"
				+ "			\"is_pending_ext_shared\": false,\n"
				+ "			\"pending_shared\": [],\n"
				+ "			\"parent_conversation\": null,\n"
				+ "			\"creator\": \"U01G251HF4K\",\n"
				+ "			\"is_ext_shared\": false,\n"
				+ "			\"shared_team_ids\": [\"TBY71ASJX\"],\n"
				+ "			\"pending_connected_team_ids\": [],\n"
				+ "			\"is_member\": false,\n"
				+ "			\"topic\": {\n"
				+ "				\"value\": \"\",\n"
				+ "				\"creator\": \"\",\n"
				+ "				\"last_set\": 0\n"
				+ "			},\n"
				+ "			\"purpose\": {\n"
				+ "				\"value\": \"\",\n"
				+ "				\"creator\": \"\",\n"
				+ "				\"last_set\": 0\n"
				+ "			},\n"
				+ "			\"previous_names\": [],\n"
				+ "			\"num_members\": 3\n"
				+ "		}, {\n"
				+ "			\"id\": \"C030RSLG7CG\",\n"
				+ "			\"name\": \"test-003\",\n"
				+ "			\"is_channel\": true,\n"
				+ "			\"is_group\": false,\n"
				+ "			\"is_im\": false,\n"
				+ "			\"is_mpim\": false,\n"
				+ "			\"is_private\": false,\n"
				+ "			\"created\": 1643104792,\n"
				+ "			\"is_archived\": false,\n"
				+ "			\"is_general\": false,\n"
				+ "			\"unlinked\": 0,\n"
				+ "			\"name_normalized\": \"test-003\",\n"
				+ "			\"is_shared\": false,\n"
				+ "			\"is_org_shared\": false,\n"
				+ "			\"is_pending_ext_shared\": false,\n"
				+ "			\"pending_shared\": [],\n"
				+ "			\"parent_conversation\": null,\n"
				+ "			\"creator\": \"U02K9E1RAUD\",\n"
				+ "			\"is_ext_shared\": false,\n"
				+ "			\"shared_team_ids\": [\"TBY71ASJX\"],\n"
				+ "			\"pending_connected_team_ids\": [],\n"
				+ "			\"is_member\": false,\n"
				+ "			\"topic\": {\n"
				+ "				\"value\": \"\",\n"
				+ "				\"creator\": \"\",\n"
				+ "				\"last_set\": 0\n"
				+ "			},\n"
				+ "			\"purpose\": {\n"
				+ "				\"value\": \"\",\n"
				+ "				\"creator\": \"\",\n"
				+ "				\"last_set\": 0\n"
				+ "			},\n"
				+ "			\"previous_names\": [],\n"
				+ "			\"num_members\": 3\n"
				+ "		}],\n"
				+ "		\"response_metadata\": {\n"
				+ "			\"next_cursor\": \"\",\n"
				+ "			\"scopes\": [\"incoming-webhook\", \"app_mentions:read\", \"channels:history\", \"channels:join\", \"channels:manage\", \"channels:read\", \"chat:write\", \"chat:write.customize\", \"commands\", \"emoji:read\", \"files:write\", \"files:read\", \"groups:history\", \"groups:read\", \"im:history\", \"im:read\", \"im:write\", \"mpim:history\", \"mpim:read\", \"mpim:write\", \"remote_files:read\", \"remote_files:share\", \"remote_files:write\", \"team:read\", \"users.profile:read\", \"users:write\", \"users:read\"],\n"
				+ "			\"acceptedScopes\": [\"channels:read\", \"groups:read\", \"mpim:read\", \"im:read\", \"read\"]\n"
				+ "		}\n"
				+ "	},\n"
				+ "	\"googleChat\": {\n"
				+ "		\"channels\": [{\n"
				+ "			\"name\": \"spaces/AAAAHIHmHdE\",\n"
				+ "			\"type\": \"ROOM\",\n"
				+ "			\"singleUserBotDm\": false,\n"
				+ "			\"threaded\": false,\n"
				+ "			\"displayName\": \"Test room\",\n"
				+ "			\"memberships\": [{\n"
				+ "				\"name\": \"spaces/AAAAHIHmHdE/members/110837451180721677114\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/110837451180721677114\",\n"
				+ "					\"displayName\": \"Madhurya Varshney\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2021-04-10T17:33:53.409444Z\"\n"
				+ "			}]\n"
				+ "		}, {\n"
				+ "			\"name\": \"spaces/AAAAHl2rgl8\",\n"
				+ "			\"type\": \"ROOM\",\n"
				+ "			\"singleUserBotDm\": false,\n"
				+ "			\"threaded\": true,\n"
				+ "			\"displayName\": \"just a testing space\",\n"
				+ "			\"memberships\": [{\n"
				+ "				\"name\": \"spaces/AAAAHl2rgl8/members/106886033806500809026\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/106886033806500809026\",\n"
				+ "					\"displayName\": \"Lalitech Test User 1\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2022-02-05T06:09:41.897810Z\"\n"
				+ "			}, {\n"
				+ "				\"name\": \"spaces/AAAAHl2rgl8/members/110837451180721677114\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/110837451180721677114\",\n"
				+ "					\"displayName\": \"Madhurya Varshney\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2021-12-04T09:32:06.699786Z\"\n"
				+ "			}]\n"
				+ "		}, {\n"
				+ "			\"name\": \"spaces/4QXTawAAAAE\",\n"
				+ "			\"type\": \"ROOM\",\n"
				+ "			\"singleUserBotDm\": false,\n"
				+ "			\"threaded\": false,\n"
				+ "			\"displayName\": \"\",\n"
				+ "			\"memberships\": [{\n"
				+ "				\"name\": \"spaces/4QXTawAAAAE/members/103410925036831005298\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/103410925036831005298\",\n"
				+ "					\"displayName\": \"Harveer Singh\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2021-04-22T05:20:14.270Z\"\n"
				+ "			}, {\n"
				+ "				\"name\": \"spaces/4QXTawAAAAE/members/110837451180721677114\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/110837451180721677114\",\n"
				+ "					\"displayName\": \"Madhurya Varshney\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2021-04-22T05:20:14.270Z\"\n"
				+ "			}]\n"
				+ "		}, {\n"
				+ "			\"name\": \"spaces/r71_8YAAAAE\",\n"
				+ "			\"type\": \"DM\",\n"
				+ "			\"singleUserBotDm\": true,\n"
				+ "			\"threaded\": false,\n"
				+ "			\"displayName\": \"\",\n"
				+ "			\"memberships\": [{\n"
				+ "				\"name\": \"spaces/r71_8YAAAAE/members/110837451180721677114\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/110837451180721677114\",\n"
				+ "					\"displayName\": \"Madhurya Varshney\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2021-12-13T06:22:42.318102Z\"\n"
				+ "			}]\n"
				+ "		}, {\n"
				+ "			\"name\": \"spaces/AAAA0aOZtk4\",\n"
				+ "			\"type\": \"ROOM\",\n"
				+ "			\"singleUserBotDm\": false,\n"
				+ "			\"threaded\": false,\n"
				+ "			\"displayName\": \"testing\",\n"
				+ "			\"memberships\": [{\n"
				+ "				\"name\": \"spaces/AAAA0aOZtk4/members/103225342601708409161\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/103225342601708409161\",\n"
				+ "					\"displayName\": \"Bhawna Varshney\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2021-04-05T06:38:18.268062Z\"\n"
				+ "			}, {\n"
				+ "				\"name\": \"spaces/AAAA0aOZtk4/members/103410925036831005298\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/103410925036831005298\",\n"
				+ "					\"displayName\": \"Harveer Singh\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2021-12-13T10:25:39.451422Z\"\n"
				+ "			}]\n"
				+ "		}, {\n"
				+ "			\"name\": \"spaces/xGuLiYAAAAE\",\n"
				+ "			\"type\": \"ROOM\",\n"
				+ "			\"singleUserBotDm\": false,\n"
				+ "			\"threaded\": false,\n"
				+ "			\"displayName\": \"\",\n"
				+ "			\"memberships\": [{\n"
				+ "				\"name\": \"spaces/xGuLiYAAAAE/members/103225342601708409161\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/103225342601708409161\",\n"
				+ "					\"displayName\": \"Bhawna Varshney\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2021-12-16T09:03:08.191263Z\"\n"
				+ "			}, {\n"
				+ "				\"name\": \"spaces/xGuLiYAAAAE/members/106886033806500809026\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/106886033806500809026\",\n"
				+ "					\"displayName\": \"Lalitech Test User 1\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2021-12-16T09:03:08.191263Z\"\n"
				+ "			}]\n"
				+ "		}, {\n"
				+ "			\"name\": \"spaces/AAAAKnsFVVE\",\n"
				+ "			\"type\": \"ROOM\",\n"
				+ "			\"singleUserBotDm\": false,\n"
				+ "			\"threaded\": false,\n"
				+ "			\"displayName\": \"Todo from Phoenix\",\n"
				+ "			\"memberships\": [{\n"
				+ "				\"name\": \"spaces/AAAAKnsFVVE/members/103225342601708409161\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/103225342601708409161\",\n"
				+ "					\"displayName\": \"Bhawna Varshney\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2022-01-25T09:24:32.561317Z\"\n"
				+ "			}, {\n"
				+ "				\"name\": \"spaces/AAAAKnsFVVE/members/106886033806500809026\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/106886033806500809026\",\n"
				+ "					\"displayName\": \"Lalitech Test User 1\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2022-01-25T09:24:32.561317Z\"\n"
				+ "			}]\n"
				+ "		}, {\n"
				+ "			\"name\": \"spaces/mJm4HoAAAAE\",\n"
				+ "			\"type\": \"DM\",\n"
				+ "			\"singleUserBotDm\": true,\n"
				+ "			\"threaded\": false,\n"
				+ "			\"displayName\": \"\",\n"
				+ "			\"memberships\": [{\n"
				+ "				\"name\": \"spaces/mJm4HoAAAAE/members/103410925036831005298\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/103410925036831005298\",\n"
				+ "					\"displayName\": \"Harveer Singh\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2021-12-04T12:26:27.822982Z\"\n"
				+ "			}]\n"
				+ "		}, {\n"
				+ "			\"name\": \"spaces/AAAAYjcKOjk\",\n"
				+ "			\"type\": \"ROOM\",\n"
				+ "			\"singleUserBotDm\": false,\n"
				+ "			\"threaded\": true,\n"
				+ "			\"displayName\": \"testing123\",\n"
				+ "			\"memberships\": [{\n"
				+ "				\"name\": \"spaces/AAAAYjcKOjk/members/103410925036831005298\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/103410925036831005298\",\n"
				+ "					\"displayName\": \"Harveer Singh\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2021-12-21T06:38:24.678601Z\"\n"
				+ "			}]\n"
				+ "		}, {\n"
				+ "			\"name\": \"spaces/AAAAYkeUMXM\",\n"
				+ "			\"type\": \"ROOM\",\n"
				+ "			\"singleUserBotDm\": false,\n"
				+ "			\"threaded\": false,\n"
				+ "			\"displayName\": \"madh\",\n"
				+ "			\"memberships\": [{\n"
				+ "				\"name\": \"spaces/AAAAYkeUMXM/members/103225342601708409161\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/103225342601708409161\",\n"
				+ "					\"displayName\": \"Bhawna Varshney\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2021-12-21T06:35:35.459693Z\"\n"
				+ "			}, {\n"
				+ "				\"name\": \"spaces/AAAAYkeUMXM/members/106886033806500809026\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/106886033806500809026\",\n"
				+ "					\"displayName\": \"Lalitech Test User 1\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2021-12-21T06:35:35.459693Z\"\n"
				+ "			}]\n"
				+ "		}, {\n"
				+ "			\"name\": \"spaces/AAAA74QWh-Q\",\n"
				+ "			\"type\": \"ROOM\",\n"
				+ "			\"singleUserBotDm\": false,\n"
				+ "			\"threaded\": false,\n"
				+ "			\"displayName\": \"front end\",\n"
				+ "			\"memberships\": [{\n"
				+ "				\"name\": \"spaces/AAAA74QWh-Q/members/103410925036831005298\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/103410925036831005298\",\n"
				+ "					\"displayName\": \"Harveer Singh\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2021-05-03T14:48:44.865381Z\"\n"
				+ "			}, {\n"
				+ "				\"name\": \"spaces/AAAA74QWh-Q/members/110837451180721677114\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/110837451180721677114\",\n"
				+ "					\"displayName\": \"Madhurya Varshney\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2021-05-03T14:48:29.167538Z\"\n"
				+ "			}, {\n"
				+ "				\"name\": \"spaces/AAAA74QWh-Q/members/115278052922037112577\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/115278052922037112577\",\n"
				+ "					\"displayName\": \"Manohar Pamishetty\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2021-05-03T14:48:44.865381Z\"\n"
				+ "			}]\n"
				+ "		}, {\n"
				+ "			\"name\": \"spaces/AAAA4zEjN8c\",\n"
				+ "			\"type\": \"ROOM\",\n"
				+ "			\"singleUserBotDm\": false,\n"
				+ "			\"threaded\": true,\n"
				+ "			\"displayName\": \"Phoenix All\",\n"
				+ "			\"memberships\": [{\n"
				+ "				\"name\": \"spaces/AAAA4zEjN8c/members/103225342601708409161\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/103225342601708409161\",\n"
				+ "					\"displayName\": \"Bhawna Varshney\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2021-04-09T20:15:46.050245Z\"\n"
				+ "			}, {\n"
				+ "				\"name\": \"spaces/AAAA4zEjN8c/members/103410925036831005298\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/103410925036831005298\",\n"
				+ "					\"displayName\": \"Harveer Singh\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2021-04-09T20:15:46.050245Z\"\n"
				+ "			}, {\n"
				+ "				\"name\": \"spaces/AAAA4zEjN8c/members/106886033806500809026\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/106886033806500809026\",\n"
				+ "					\"displayName\": \"Lalitech Test User 1\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2022-03-21T04:33:33.227177Z\"\n"
				+ "			}, {\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"name\": \"spaces/AAAA4zEjN8c/members/110837451180721677114\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/110837451180721677114\",\n"
				+ "					\"displayName\": \"Madhurya Varshney\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2021-04-09T20:15:46.050245Z\"\n"
				+ "			}, {\n"
				+ "				\"name\": \"spaces/AAAA4zEjN8c/members/111632116727691744406\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/111632116727691744406\",\n"
				+ "					\"displayName\": \"Govind Varshney\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2021-04-09T20:15:45.392043Z\"\n"
				+ "			}, {\n"
				+ "				\"name\": \"spaces/AAAA4zEjN8c/members/115278052922037112577\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/115278052922037112577\",\n"
				+ "					\"displayName\": \"Manohar Pamishetty\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2021-04-09T20:15:46.050245Z\"\n"
				+ "			}, {\n"
				+ "				\"name\": \"spaces/AAAA4zEjN8c/members/115878802501641088813\",\n"
				+ "				\"state\": \"JOINED\",\n"
				+ "				\"member\": {\n"
				+ "					\"name\": \"users/115878802501641088813\",\n"
				+ "					\"displayName\": \"Manish Kumar Singh\",\n"
				+ "					\"domainId\": \"27wizzn\",\n"
				+ "					\"type\": \"HUMAN\",\n"
				+ "					\"isAnonymous\": false\n"
				+ "				},\n"
				+ "				\"createTime\": \"2021-04-09T20:15:46.050245Z\"\n"
				+ "			}]\n"
				+ "		}]\n"
				+ "	}\n"
				+ "}";
		
		JSONObject object = new JSONObject(jsonFile);
//		String sData = object.get("slack").toString();
		JSONObject sData = object.getJSONObject("slack");
//		String sData = object.getString("slack");
//		String sData = (String) slackData;
		System.out.println("***********************");
//		System.out.println("errorMessage : " + sData);
		
//		JsonParser parser = new JsonParser();
//		JsonElement jsonResponse = parser.parse(sData);
//		int sizeofArray = jsonResponse.getAsJsonArray().size();
//		JsonElement jElement = jsonResponse.getAsJsonArray().get(0);
////		System.out.println("Response of availableRoomsForUsers second element is :-> " + jsonResponse.getAsJsonArray().get(1));
//		JsonObject responseJson = jElement.getAsJsonObject();
//		String Id = responseJson.get("id").getAsString();
//		System.out.println("Id :-> "+ Id);
//		JSONArray jsonArray = (JSONArray) sData.get("error");
//		Object errorRes = jsonArray.get(0);
//		String fetchErrorRes = (String) errorRes;
//		System.out.println("Fetch Error from Registration  : " + fetchErrorRes);
		

	}

}
